title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://qbona12.github.io/praca_zaliczeniowa

aux_links
: # remove if you don't want this link to appear on your pages
Template Repository: https://qbona12.github.io/praca_zaliczeniowa